Created auto git file reset after version number update.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -11,14 +11,25 @@
 
 GIT_DIR_="$(git rev-parse --git-dir)"
 
+currentVersion=$(git diff --name-only --cached)
 
-if sh $GIT_DIR_/../updateVersion.sh build; then
-    echo "Successfully ran updateVersion.sh"
-    exit 0
+
+if [[ $currentVersion == *"galileo.sma"* ]]
+then
+    if sh $GIT_DIR_/../updateVersion.sh build
+    then
+        echo "isToUpdateTheGalileoFile" > $GIT_DIR_/isToUpdateTheGalileoFile.txt
+        echo "Successfully ran updateVersion.sh"
+        exit 0
+    else
+        echo "Could not update updateVersion.sh right!"
+        exit 1
+    fi
 else
-    echo "Could not update updateVersion.sh right!"
-    exit 1
+    echo "The 'galileo.sma' file is not being committed right now."
 fi
 
+
+exit 0
 
 
