Created the file "__post-git-hook.sh" to remove code redudancy on the git hook files.

diff --git a/githooks/post-checkout b/githooks/post-checkout
--- a/githooks/post-checkout
+++ b/githooks/post-checkout
@@ -17,43 +17,34 @@
 #      of git-checkout.
 
 
+
 echo "Running the post-checkout hook..."
 
+
+GIT_DIR_="$(git rev-parse --git-dir)"
+updateVersionScript=$GIT_DIR_/../githooks/__post-git-hook.sh
 
 currentBranch=$(basename $(git symbolic-ref HEAD))
 commitsBehindDevelop=$(git rev-list --count $currentBranch..develop)
 
 
-GIT_DIR_="$(git rev-parse --git-dir)"
-updateVersionProgram=githooks/updateVersion.sh
-
-
-
+# Alert the user when his checkout branch is behind the develop branch.
 if [ $commitsBehindDevelop -gt 0 ]
 then
     printf "ATTENTION: Your branch $currentBranch is $commitsBehindDevelop commits behind develop\n"
     exit 1
 fi
 
-
-# Updates and changes the files if the flag file exits.
-if [ -f $GIT_DIR_/isToUpdateTheGalileoFile.txt ]
+# Run the version update script.
+if sh $updateVersionScript
 then
-    sh $GIT_DIR_/../$updateVersionProgram build
-    echo "Amending commits..."
-    git commit --amend -C HEAD --no-verify
+    echo "The post-checkout hook successfully ran $updateVersionScript."
 else
-    echo "It is not time amend as the file 'isToUpdateTheGalileoFile.txt' does not exist."
+    echo "Could not run the update program $updateVersionScript properly!"
+    exit 1
 fi
 
 
-# To clean any old missed file
-if [ -f $GIT_DIR_/isToUpdateTheGalileoFile.txt ]
-then
-    echo "Removing old post-commit configuration file 'isToUpdateTheGalileoFile.txt'..."
-    rm $GIT_DIR_/isToUpdateTheGalileoFile.txt
-fi
-
+# Exits the program using a successful exit status code.
 exit 0
-
 
