Fixed bad flag file name and merged two if condiditional on "prepare-commit-msg" git hook.

diff --git a/githooks/prepare-commit-msg b/githooks/prepare-commit-msg
--- a/githooks/prepare-commit-msg
+++ b/githooks/prepare-commit-msg
@@ -32,11 +32,11 @@ versionFilePath=$GIT_DIR_/../$(echo $githooksConfig | cut -d',' -f 1)
 # $filePathToUpdate example: scripting/galileo.sma
 filePathToUpdate=$GIT_DIR_/../$(echo $githooksConfig | cut -d',' -f 2)
 
-# $fileNameToUpdate example: galileo.sma
-fileNameToUpdate=$GIT_DIR_/../$(echo $githooksConfig | cut -d',' -f 3)
+# $updateFlagFilePath example: isToUpdateTheGalileoFile.txt
+updateFlagFilePath=$GIT_DIR_/$(echo $githooksConfig | cut -d',' -f 4)
 
-# $updateFlagFileName example: isToUpdateTheGalileoFile.txt
-updateFlagFileName=$GIT_DIR_/$(echo $githooksConfig | cut -d',' -f 4)
+# $fileNameToUpdate example: galileo.sma
+fileNameToUpdate=$(echo $githooksConfig | cut -d',' -f 3)
 
 currentGitFiles=$(git diff --name-only --cached)
 currentBranch=$(basename $(git symbolic-ref HEAD))
@@ -44,42 +44,47 @@ currentBranch=$(basename $(git symbolic-ref HEAD))
 currentVersion=$(cat $versionFilePath)
 
 
-# When the file "$updateFlagFileName" exits, we must not to recreate it, as we just did
-# that. This happens because the file "$updateFlagFileName" is created to indicate that
+# When the file "$updateFlagFilePath" exits, we must not to recreate it, as we just did
+# that. This happens because the file "$updateFlagFilePath" is created to indicate that
 # the version number already updated and doing it again would create an infinite loop.
 # Because this is a recursive shell script, hence this file is recalled later and it
 # must to be stopped right here.
-if [ -f $updateFlagFileName ]
+if [ -f $updateFlagFilePath ]
 then
-    echo "Removing old prepare-commmit-message configuration file '$updateFlagFileName'..."
-    rm $updateFlagFileName
+    echo "Removing old prepare-commmit-message configuration file '$updateFlagFilePath'..."
+    rm $updateFlagFilePath
     exit 0
 fi
 
 
-# To prints a error message when it does not find the version number on the file.
-#
-# 'F' affects how PATTERN is interpreted (fixed string instead of a regex).
-# 'q' shhhhh... minimal printing.
-#
-if [[ $currentGitFiles == *"$fileNameToUpdate"* ]] && !grep -F "v$currentVersion" "$filePathToUpdate"
+# If the $fileNameToUpdate is not being committed right now, do nothing.
+if [[ $currentGitFiles == *"$fileNameToUpdate"* ]]
 then
-    echo "Error! Could not find v$currentVersion and update the file '$filePathToUpdate'."
-    echo "The current version number on this file must be v$currentVersion."
-    echo "Or fix the file '$versionFilePath' to the correct value."
-    exit 1
-fi
-
-
-# This creates the flag file '$updateFlagFileName' to indicate that 'post-checkout' and
-# 'post-commit' hooks must to update the version number. It only updates whether the current
-# branch the develop and the file being changed is "$fileNameToUpdate".
-if [[ $currentGitFiles == *"$fileNameToUpdate"* ]] && [[ $currentBranch == "develop" ]]
-then
-    echo "true" > $updateFlagFileName
-    echo "Successfully created the flag file '$updateFlagFileName'"
+    # To prints a error message when it does not find the version number on the file.
+    #
+    # 'F' affects how PATTERN is interpreted (fixed string instead of a regex).
+    # 'q' shhhhh... minimal printing.
+    #
+    if ! grep -Fq "v$currentVersion" "$filePathToUpdate"
+    then
+        echo "Error! Could not find v$currentVersion and update the file '$filePathToUpdate'."
+        echo "The current version number on this file must be v$currentVersion."
+        echo "Or fix the file '$versionFilePath' to the correct value."
+        exit 1
+    fi
+    
+    # This creates the flag file '$updateFlagFilePath' to indicate that 'post-checkout' and
+    # 'post-commit' hooks must to update the version number. It only updates whether the current
+    # branch the develop and the file being changed is "$fileNameToUpdate".
+    if [[ $currentBranch == "develop" ]]
+    then
+        echo "true" > $updateFlagFilePath
+        echo "Successfully created the flag file '$updateFlagFilePath'"
+    else
+        echo "The '$fileNameToUpdate' file is not being updated we are not on the 'develop' branch."
+    fi
 else
-    echo "The '$fileNameToUpdate' file is not being updated right now."
+    echo "The '$fileNameToUpdate' file is not being committed right now."
 fi
 
 
